name: Semantic PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
  
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - run: echo "xxxxxxx"
      - run: echo ${#${{secrets.TEST}}}        

